### ISSUE TITLE
Endnotes to Footnotes

### ISSUE THREAD

**Issue by sebastianlueders** [bennettscience/endnotes#15]
Is there any way of reversing this process, and converting endnotes to footnotes so that I can edit? Or should I just use Word.

**Comment by bennettscience** [comment]
Because the original footnote locations are not stored, the best method is
to do all of your writing, including adding and editing footnotes. When
your draft is nearly complete and more importantly, your *footnotes* are
complete, run the conversion and check your footnotes. If you notice an
issue, you can use the undo option in Docs to revert. You can also look at
the Docs revision history and revert to an earlier version of the document.

Brian E. Bennett
Web: ohheybrian.com
Twitter: @bennettscience <http://www.twitter.com/#!/bennettscience>
574.323.8519
