### ISSUE TITLE
Simply doesn't work

### ISSUE THREAD

**Issue by cjcornell** [bennettscience/endnotes#3]
Very disappointing. I installed.  Opened a document that has lots of footnotes.'
Went to menu  Add -ons-> End Note Generator .
and the only sub menu is "help"
no Run.

And that's that.

**Comment by bennettscience** [comment]
Try reloading the document. I've had a couple others emailing with the same behavior. A reload seems to help in the short run. I'm going to look into the issue in the next day and push an update. Sorry for the problems.

**Comment by cjcornell** [comment]
didn't work (that was the first thing I tried).  That's OK my document is unusual. I uploaded from word .. it's an entire book - very large (300 pages ... 200+ endnotes).

**Comment by bennettscience** [comment]
Yeah, that's a biggie. Not sure how it would run anyways with that many footnotes.

The bug should be worked out now. I've done a lot of testing today and haven't run into the issue with the latest version of the addon. Let me know if it's resolved and I can close the issue.

**Comment by cjcornell** [comment]
hmmm ... I tried it (even though my immediate need has passed).  Just to give you some feedback.
My first set of attempts didn't work - but I was using the same document as my early attempts so .. I started over:
Uploaded the word document (book), with several hundred endnotes.
let gdoc convert to a document...  and Gdoc promptly converted to chapter footnotes
ran the Add-on.
It converted to endnotes ....  with some caveats - FYI for future tweaking.
A. I originally had my endnotes organized by chapter - restarting the numbering for each. Now they are all one set of numbering (which is OK ... just FYI)

B Since I have a long document and lots of footnotes, some comments from that perspective ... whether or not I am a rare case:
- since it takes a few mins to generate the endnotes (and the doc is unresponsive) ... some kind of visual progress would be very nice so the user doesn't think they're locked up. or keep clicking.

Thanks for replying so quickly!

**Comment by bennettscience** [comment]
Thanks for such detailed feedback.

When I built this, it was mainly for students writing shorter reports. I can definitely see the cases for chapters. I'll look into that as an improvement to add in.

Right now, it's pretty brute force, meaning I take *all* the footnotes and then run them all at once. I have some ideas about how to store the number of footnotes for a doc so you can run it again and add more in the future rather than waiting until the end. Making that change will also make it easier to display the number converted.

Thanks again for using!

**Comment by cjcornell** [comment]
my pleasure. Addons like this have a good market for $$ customers.
