### ISSUE TITLE
Retaining font type & other formatting?

### ISSUE THREAD

**Issue by MMWong** [bennettscience/endnotes#6]
This generator works amazingly most of the time. The only thing I'd suggest is to, if possible, retain the font type and formatting style of the original footnotes, such as _italic_ and **bold** text.

**Comment by bennettscience** [comment]
Good idea. I wasn't in the habit of formatting my notes. I need to set some time aside to work on it. Thanks for the suggestion.

**Comment by jradamson** [comment]
I second this request! I use links in my endnotes, and the generator removes the hyperlinks when replacing the footnotes with endnotes. Other that, it would work perfectly for me!

**Comment by 1nsertNameHere** [comment]
I'd also like this feature very much, as I am having to go through everything to manually italicize. Other than that, this is a live saver, thank you!

**Comment by bennettscience** [comment]
This feature is implemented in the current version of the addon.

In order to retain formatting, endnotes are now added as sequential paragraphs rather than a list. Inserting or removing notes **will no longer** update the sequence automatically. This has to do with the way I was able to get the formatting information when creating the notes.
